language: java
before_install:
  - wget --timeout=30 http://dl.google.com/android/ndk/android-ndk-r8e-linux-x86.tar.bz2 -O ndk.tar.bz2
  - tar -xf ndk.tar.bz2
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
before_script: 
  - sudo wget -q http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - sudo tar xzvf http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz > /dev/null
  - sudo $ANDROID_HOME/tools/android -s update sdk --filter android-10,platform-tool --no-ui
  - sudo $ANDROID_HOME/tools/android -s update project --path . --target "android-10"
  - sudo chmod -R 777 ./*
script:
  - make